name: 'Free Association '
favicon: null
layout_spectrum: 0.7768970516044647
typography_spectrum: 0.4526128554716706
title: 'Free Association '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6fcfc'
    - '#c1abb7'
    - '#2d363f'
    - '#987887'
    - '#983941'
  brandStrength: 0.6875
  lightness: 0.8964038339909166
  saturation: 0.15613503474742174
  rhythmicContrast: 0.23319319146685302
purpose: []
